// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listBoards: () => __TAURI_INVOKE<Board[]>("list_boards"),
	createBoard: (input: NewBoard) => __TAURI_INVOKE<Board>("create_board", { input }),
	listProjects: () => __TAURI_INVOKE<Project[]>("list_projects"),
	createProject: (boardId: string, name: string) => __TAURI_INVOKE<Project>("create_project", { boardId, name }),
	renameProject: (id: string, name: string) => __TAURI_INVOKE<Project>("rename_project", { id, name }),
	/**  The project's tickets stay on the board, without a project. */
	deleteProject: (id: string) => __TAURI_INVOKE<null>("delete_project", { id }),
	listLabels: () => __TAURI_INVOKE<Label[]>("list_labels"),
	createLabel: (name: string, color: Color) => __TAURI_INVOKE<Label>("create_label", { name, color }),
	updateLabel: (id: string, patch: LabelPatch) => __TAURI_INVOKE<Label>("update_label", { id, patch }),
	/**  Also removes it from every ticket. */
	deleteLabel: (id: string) => __TAURI_INVOKE<null>("delete_label", { id }),
	/**  Adds the label to the ticket, or removes it when `applied` is false. */
	setTicketLabel: (ticketId: string, labelId: string, applied: boolean) => __TAURI_INVOKE<Ticket>("set_ticket_label", { ticketId, labelId, applied }),
	/**  Tickets on a board, or in the Inbox when `board_id` is `None`. */
	listTickets: (boardId: string | null) => __TAURI_INVOKE<Ticket[]>("list_tickets", { boardId }),
	/**  Tickets on every board and in the Inbox, best matches first. */
	searchTickets: (query: string) => __TAURI_INVOKE<Ticket[]>("search_tickets", { query }),
	/**  My Focus: open tickets anywhere that are in progress, in review, or due by `due_by`. */
	listFocus: (dueBy: string) => __TAURI_INVOKE<Ticket[]>("list_focus", { dueBy }),
	/**  New tickets go to the top of their status group. */
	createTicket: (input: NewTicket) => __TAURI_INVOKE<Ticket>("create_ticket", { input }),
	updateTicket: (id: string, patch: TicketPatch) => __TAURI_INVOKE<Ticket>("update_ticket", { id, patch }),
	/**
	 *  Moves a ticket to a board (or the Inbox when `board_id` is `None`) and a project on it
	 *  (or none). Changing boards gives the ticket that board's next number.
	 */
	moveTicket: (id: string, boardId: string | null, projectId: string | null) => __TAURI_INVOKE<Ticket>("move_ticket", { id, boardId, projectId }),
	/**  Places a ticket at an exact status and position, e.g. after a drag and drop. */
	repositionTicket: (id: string, status: Status, position: number | null) => __TAURI_INVOKE<Ticket>("reposition_ticket", { id, status, position }),
	/**  Permanently deletes a ticket with its checklist and labels. */
	deleteTicket: (id: string) => __TAURI_INVOKE<null>("delete_ticket", { id }),
	/**  `due_date` is `YYYY-MM-DD`, or `None` to clear it. */
	setDueDate: (id: string, dueDate: string | null) => __TAURI_INVOKE<Ticket>("set_due_date", { id, dueDate }),
	listChecklist: (ticketId: string) => __TAURI_INVOKE<ChecklistItem[]>("list_checklist", { ticketId }),
	addChecklistItem: (ticketId: string, text: string) => __TAURI_INVOKE<ChecklistItem>("add_checklist_item", { ticketId, text }),
	updateChecklistItem: (id: string, patch: ChecklistPatch) => __TAURI_INVOKE<ChecklistItem>("update_checklist_item", { id, patch }),
	deleteChecklistItem: (id: string) => __TAURI_INVOKE<null>("delete_checklist_item", { id }),
	/**  Archived tickets from every board and the Inbox, most recently finished first. */
	listArchived: () => __TAURI_INVOKE<Ticket[]>("list_archived"),
	/**  Archives Done tickets that are due, if auto-archive is on. Returns how many it archived. */
	autoArchive: () => __TAURI_INVOKE<number>("auto_archive"),
	/**  Brings a ticket back from the Archive to the top of its status group. */
	restoreTicket: (id: string) => __TAURI_INVOKE<Ticket>("restore_ticket", { id }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**  Saves the settings, then archives anything they now make due. */
	updateSettings: (settings: Settings) => __TAURI_INVOKE<Settings>("update_settings", { settings }),
};

/* Types */
export type Board = {
	id: string,
	name: string,
	key: string,
	color: Color,
};

export type ChecklistItem = {
	id: string,
	ticketId: string,
	text: string,
	done: boolean,
	position: number | null,
};

/**  Fields left as `None` are unchanged. */
export type ChecklistPatch = {
	text: string | null,
	done: boolean | null,
};

export type Color = "gray" | "red" | "orange" | "yellow" | "green" | "blue" | "purple" | "pink";

export type Label = {
	id: string,
	name: string,
	color: Color,
};

/**  Fields left as `None` are unchanged. */
export type LabelPatch = {
	name: string | null,
	color: Color | null,
};

export type NewBoard = {
	name: string,
	key: string,
	color: Color,
};

export type NewTicket = {
	/**  `None` creates the ticket in the Inbox. */
	boardId: string | null,
	/**  Must belong to `board_id`. */
	projectId: string | null,
	title: string,
	status: Status,
	priority: Priority,
};

export type Priority = "none" | "low" | "medium" | "high" | "urgent";

export type Project = {
	id: string,
	boardId: string,
	name: string,
};

export type Settings = {
	/**  Moves Done tickets to the Archive once they've been done for `archive_after_days`. */
	autoArchive: boolean,
	archiveAfterDays: number,
};

export type Status = "backlog" | "ready" | "in_progress" | "in_review" | "done" | "canceled";

export type Ticket = {
	id: string,
	boardId: string | null,
	boardKey: string | null,
	projectId: string | null,
	number: number | null,
	title: string,
	description: string,
	status: Status,
	priority: Priority,
	dueDate: string | null,
	position: number | null,
	completedAt: number | null,
	checklistDone: number,
	checklistTotal: number,
	labelIds: string[],
	/**  Set while the ticket is in the Archive. */
	archivedAt: number | null,
};

/**  Fields left as `None` are unchanged. */
export type TicketPatch = {
	title: string | null,
	/**  Markdown. */
	description: string | null,
	status: Status | null,
	priority: Priority | null,
};

