// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listBoards: () => __TAURI_INVOKE<Board[]>("list_boards"),
	createBoard: (input: NewBoard) => __TAURI_INVOKE<Board>("create_board", { input }),
	/**  Tickets on a board, or in the Inbox when `board_id` is `None`. */
	listTickets: (boardId: string | null) => __TAURI_INVOKE<Ticket[]>("list_tickets", { boardId }),
	/**  New tickets go to the top of their status group. */
	createTicket: (input: NewTicket) => __TAURI_INVOKE<Ticket>("create_ticket", { input }),
	updateTicket: (id: string, patch: TicketPatch) => __TAURI_INVOKE<Ticket>("update_ticket", { id, patch }),
	/**
	 *  Moves a ticket to another board, or to the Inbox when `board_id` is `None`.
	 *  The ticket gets a new number on the destination board and leaves its project.
	 */
	moveTicket: (id: string, boardId: string | null) => __TAURI_INVOKE<Ticket>("move_ticket", { id, boardId }),
};

/* Types */
export type Board = {
	id: string,
	name: string,
	key: string,
	color: BoardColor,
};

export type BoardColor = "gray" | "red" | "orange" | "yellow" | "green" | "blue" | "purple" | "pink";

export type NewBoard = {
	name: string,
	key: string,
	color: BoardColor,
};

export type NewTicket = {
	/**  `None` creates the ticket in the Inbox. */
	boardId: string | null,
	title: string,
	status: Status,
	priority: Priority,
};

export type Priority = "none" | "low" | "medium" | "high" | "urgent";

export type Status = "backlog" | "ready" | "in_progress" | "in_review" | "done" | "canceled";

export type Ticket = {
	id: string,
	boardId: string | null,
	boardKey: string | null,
	projectId: string | null,
	number: number | null,
	title: string,
	description: string,
	status: Status,
	priority: Priority,
	dueDate: string | null,
	position: number | null,
	completedAt: number | null,
};

/**  Fields left as `None` are unchanged. */
export type TicketPatch = {
	title: string | null,
	status: Status | null,
	priority: Priority | null,
};

